volumes:
  gmfs-data-vol:
  gmfs-git-vol:
services:
  # Main Services
  gm-file-server-init:
    image: glidein-manager-file-server
    build: .
    volumes:
      - gmfs-data-vol:/etc/gm-file-server/data
      - ./volumes/sql:/tmp/sql
    entrypoint: 
      - sh
      - -c
      - >
        sqlite3 /etc/gm-file-server/data/db.sqlite -init /tmp/sql/init_local_db.sql; 
        chown apache:apache /etc/gm-file-server/data/db.sqlite
  gm-file-server:
    image: glidein-manager-file-server
    build: .
    depends_on:
      - gm-file-server-init
    environment:
      - REPO_URL=git@github.com:mwestphall/glidein-manager-test-upstream.git
      - SSH_KEY=/mnt/ssh/id_rsa
      - API_PREFIX=/api
    volumes:
      - ./volumes/ssh/:/mnt/ssh:ro
      - gmfs-git-vol:/var/lib/git
      - gmfs-data-vol:/etc/gm-file-server/data
    ports:
      - "8080:80"

  # Test Containers
  sample-client:
    image: glidein-manager-file-server
    build: .
    depends_on:
      - gm-file-server
    environment:
      - API_PREFIX=/api
      - GM_ADDRESS=http://gm-file-server
      - CALLBACK_ADDRESS=http://sample-client:8089/public/challenge/response
      - CLIENT_NAME=sample-client
    working_dir: /srv/app
    entrypoint: ['uvicorn', 'test.test_client:app', '--host', '0.0.0.0', '--port', '8089']

  db-profile:
    profiles: ["db-test"]
    image: glidein-manager-file-server
    build: .
    environment:
      - API_PREFIX=/api
      - GM_ADDRESS=http://gm-file-server
      - CALLBACK_ADDRESS=http://sample-client:8089/public/challenge/response
      - CLIENT_NAME=sample-client
    working_dir: /srv/app
    entrypoint: ['python3', '-m', 'test.benchmark_db']
    volumes:
      - gmfs-data-vol:/etc/gm-file-server/data
