volumes:
  gmfs-data-vol:
  gmfs-git-vol:
services:
  # Main Service
  gm-file-server:
    image: glidein-manager-file-server
    build: .
    environment:
      - REPO_URL=git@github.com:mwestphall/glidein-manager-test-upstream.git
      - SSH_KEY=/mnt/ssh/id_rsa
      - API_PREFIX=/api
    volumes:
      - ./volumes/ssh/:/mnt/ssh:ro
      - gmfs-git-vol:/var/lib/git
      - gmfs-data-vol:/etc/gm-file-server/data
    ports:
      - "8080:80"

  # Test Containers
  sample-client: &test-container
    build:
      context: .
      dockerfile: tests.Dockerfile
    profiles: ["auth-exchange-test"]
    env_file:
      - tests.env
    image: glidein-manager-tests
    depends_on:
      - gm-file-server
    environment:
      - API_PREFIX=/api
      - GM_ADDRESS=http://gm-file-server
      - CALLBACK_ADDRESS=http://sample-client:8089/public/challenge/response
      - CLIENT_NAME=sample-client
    working_dir: /srv/app
    volumes:
      - gmfs-data-vol:/etc/gm-file-server/data
    entrypoint: ['uvicorn', 'test.test_auth_exchange:app', '--host', '0.0.0.0', '--port', '8089']

  git-pull:
    <<: *test-container
    profiles: ["tests"]
    entrypoint: ['python3', '-m', 'pytest', 'test/pytest']


  db-profile:
    profiles: ["db-test"]
    image: glidein-manager-file-server
    build: .
    environment:
      - API_PREFIX=/api
      - GM_ADDRESS=http://gm-file-server
      - CALLBACK_ADDRESS=http://sample-client:8089/public/challenge/response
      - CLIENT_NAME=sample-client
    working_dir: /srv/app
    entrypoint: ['python3', '-m', 'test.benchmark_db']
    volumes:
      - gmfs-data-vol:/etc/gm-file-server/data
